trainer:
  nnodes: 1
  n_gpus_per_node: 4

data:
  task_name: "task"
  path: ./data/test/parquet/test.parquet
  prompt_key: prompt
  n_samples: 1
  output_path: null
  batch_size: 32

model:
  path: deepseek-ai/DeepSeek-R1-Distill-Qwen-14B
  external_lib: null
  load_param: False
  load_param_path: null
  lora_rank: 0
  lora_alpha: 0
  target_modules: all-linear

rollout:
  name: vllm
  mode: sync # sync: LLM, async: AsyncLLM
  temperature: 0.0
  top_k: -1 # 0 for hf rollout, -1 for vllm rollout
  top_p: 1.0
  prompt_length: 2500
  response_length: 700
  # for vllm rollout
  dtype: bfloat16 # should align with FSDP
  gpu_memory_utilization: 0.5
  ignore_eos: False
  enforce_eager: True
  free_cache_engine: True
  load_format: dummy_dtensor
  tensor_model_parallel_size: 4
  max_num_batched_tokens: 8192
  max_model_len: null
  max_num_seqs: 1024
  log_prob_micro_batch_size: null # will be deprecated, use log_prob_micro_batch_size_per_gpu
  log_prob_micro_batch_size_per_gpu: 8
  # for fire vllm rollout
  use_fire_sampling: False # enable FIRE https://arxiv.org/abs/2410.21236
  # for hf rollout
  do_sample: True
  disable_log_stats: False
  enable_chunked_prefill: True
  n: 1
  # if beam search activated, top_k, temperature and top_p will be ignored
    
actor:
  strategy: fsdp  # This is for backward-compatibility
  ulysses_sequence_parallel_size: 1 # sp size
  fsdp_config:
    fsdp_size: -1
    forward_prefetch: False
    
ray_init:
  num_cpus: null # `None` means using all CPUs, which might cause hang if limited in systems like SLURM. Please set to a number allowed then.
  timeline_json_file: null