
data:
  task_name: "task"
  train_batch_size: 8
  micro_batch_size: null # will be deprecated, use micro_batch_size_per_gpu
  micro_batch_size_per_gpu: 1  # this is also val batch size
  path: ./data/folder_name
  train_files: ${data.path}/parquet/train.parquet
  val_files: ${data.path}/parquet/valid.parquet
  # Single-turn settings
  prompt_key: "prompt"
  response_key: "answer"
  # Multi-turn settings
  multiturn:
    enable: false  # Set to true to use multi-turn dataset
    messages_key: messages  # Key for messages list in multi-turn mode
  max_length: 2600
  truncation: error
  balance_dp_token: True
  chat_template: null
  custom_cls:
    path: null
    name: null

model:
  partial_pretrain: deepseek-ai/DeepSeek-R1-Distill-Qwen-14B
  fsdp_config:
    wrap_policy:
      min_num_params: 0
    cpu_offload: False
    offload_params: False
  external_lib: null
  enable_gradient_checkpointing: True
  trust_remote_code: False
  lora_rank: 0  # Set to positive value to enable LoRA (e.g., 32)
  lora_alpha: 16  # LoRA scaling factor
  target_modules: all-linear  # Target modules for LoRA adaptation
  use_liger: False
optim:
  lr_scheduler: cosine
  lr: 1e-5
  betas: [0.9, 0.95]
  weight_decay: 0.01
  warmup_steps_ratio: 0.02
  clip_grad: 1.0
ulysses_sequence_parallel_size: 1
use_remove_padding: False
trainer:
  default_local_dir: checkpoints/sft/${trainer.project_name}/${trainer.experiment_name}
  default_hdfs_dir: null #hdfs://tmp/experiments/gsm8k/gemma-1.1-7b-it/ # change the hdfs path here
  resume_path: null
  project_name: "Project"
  experiment_name: "Experiment"
  total_epochs: 4
  total_training_steps: null
  logger: ['console', 'wandb']
  seed: 1

actor_rollout_ref:
  processor: null # not use processor
